CREATE TABLE IF NOT EXISTS temu_sales_snapshot (
  id TEXT PRIMARY KEY,
  tenant_id TEXT NOT NULL,
  skc_id TEXT NOT NULL,
  product_id TEXT,
  goods_id TEXT,
  mall_supplier_id TEXT,
  title TEXT,
  category_name TEXT,
  thumb_url TEXT,
  sku_ext_code TEXT,
  today_sales INTEGER,
  last7d_sales INTEGER,
  last30d_sales INTEGER,
  total_sales INTEGER,
  warehouse_stock INTEGER,
  occupy_stock INTEGER,
  unavailable_stock INTEGER,
  advice_qty INTEGER,
  available_sale_days REAL,
  declared_price_cents INTEGER,
  price_currency TEXT,
  asf_score TEXT,
  comment_num INTEGER,
  quality_after_sales_rate TEXT,
  supply_status TEXT,
  stock_status TEXT,
  close_jit_status TEXT,
  stat_date TEXT NOT NULL,
  sources_json TEXT,
  first_seen_at TEXT NOT NULL DEFAULT (datetime('now')),
  last_updated_at TEXT NOT NULL DEFAULT (datetime('now')),
  UNIQUE (tenant_id, skc_id, stat_date)
);

CREATE INDEX IF NOT EXISTS idx_temu_sales_tenant_date ON temu_sales_snapshot(tenant_id, stat_date);
