CREATE TABLE IF NOT EXISTS erp_inbound_receipts (
  id TEXT PRIMARY KEY,
  account_id TEXT NOT NULL,
  po_id TEXT,
  receipt_no TEXT NOT NULL,
  status TEXT NOT NULL DEFAULT 'pending_arrival',
  received_at TEXT,
  operator_id TEXT,
  remark TEXT,
  created_at TEXT NOT NULL,
  updated_at TEXT NOT NULL,
  UNIQUE(account_id, receipt_no),
  FOREIGN KEY(account_id) REFERENCES erp_accounts(id),
  FOREIGN KEY(po_id) REFERENCES erp_purchase_orders(id),
  FOREIGN KEY(operator_id) REFERENCES erp_users(id)
);

CREATE TABLE IF NOT EXISTS erp_inbound_receipt_lines (
  id TEXT PRIMARY KEY,
  account_id TEXT NOT NULL,
  receipt_id TEXT NOT NULL,
  po_line_id TEXT,
  sku_id TEXT NOT NULL,
  expected_qty INTEGER DEFAULT 0,
  received_qty INTEGER NOT NULL,
  damaged_qty INTEGER DEFAULT 0,
  shortage_qty INTEGER DEFAULT 0,
  over_qty INTEGER DEFAULT 0,
  batch_id TEXT,
  FOREIGN KEY(account_id) REFERENCES erp_accounts(id),
  FOREIGN KEY(receipt_id) REFERENCES erp_inbound_receipts(id),
  FOREIGN KEY(po_line_id) REFERENCES erp_purchase_order_lines(id),
  FOREIGN KEY(sku_id) REFERENCES erp_skus(id)
);

CREATE TABLE IF NOT EXISTS erp_inventory_batches (
  id TEXT PRIMARY KEY,
  account_id TEXT NOT NULL,
  batch_code TEXT NOT NULL,
  sku_id TEXT NOT NULL,
  po_id TEXT,
  inbound_receipt_id TEXT,
  received_qty INTEGER NOT NULL,
  available_qty INTEGER NOT NULL DEFAULT 0,
  reserved_qty INTEGER NOT NULL DEFAULT 0,
  blocked_qty INTEGER NOT NULL DEFAULT 0,
  defective_qty INTEGER NOT NULL DEFAULT 0,
  rework_qty INTEGER NOT NULL DEFAULT 0,
  unit_landed_cost REAL NOT NULL DEFAULT 0,
  qc_status TEXT NOT NULL DEFAULT 'pending',
  location_code TEXT,
  received_at TEXT NOT NULL,
  created_at TEXT NOT NULL,
  updated_at TEXT NOT NULL,
  UNIQUE(account_id, batch_code),
  FOREIGN KEY(account_id) REFERENCES erp_accounts(id),
  FOREIGN KEY(sku_id) REFERENCES erp_skus(id),
  FOREIGN KEY(po_id) REFERENCES erp_purchase_orders(id),
  FOREIGN KEY(inbound_receipt_id) REFERENCES erp_inbound_receipts(id)
);

CREATE TABLE IF NOT EXISTS erp_inventory_ledger_entries (
  id TEXT PRIMARY KEY,
  account_id TEXT NOT NULL,
  sku_id TEXT NOT NULL,
  batch_id TEXT,
  type TEXT NOT NULL,
  qty_delta INTEGER NOT NULL,
  from_bucket TEXT,
  to_bucket TEXT,
  unit_cost REAL,
  source_doc_type TEXT NOT NULL,
  source_doc_id TEXT NOT NULL,
  created_at TEXT NOT NULL,
  created_by TEXT,
  FOREIGN KEY(account_id) REFERENCES erp_accounts(id),
  FOREIGN KEY(sku_id) REFERENCES erp_skus(id),
  FOREIGN KEY(batch_id) REFERENCES erp_inventory_batches(id),
  FOREIGN KEY(created_by) REFERENCES erp_users(id)
);

CREATE TABLE IF NOT EXISTS erp_qc_inspections (
  id TEXT PRIMARY KEY,
  account_id TEXT NOT NULL,
  batch_id TEXT NOT NULL,
  sku_id TEXT NOT NULL,
  status TEXT NOT NULL DEFAULT 'pending_qc',
  suggested_sample_qty INTEGER DEFAULT 0,
  actual_sample_qty INTEGER DEFAULT 0,
  defective_qty INTEGER DEFAULT 0,
  defect_rate REAL DEFAULT 0,
  defect_types_json TEXT NOT NULL DEFAULT '[]',
  release_qty INTEGER DEFAULT 0,
  blocked_qty INTEGER DEFAULT 0,
  rework_qty INTEGER DEFAULT 0,
  photos_json TEXT NOT NULL DEFAULT '[]',
  inspector_id TEXT,
  remark TEXT,
  created_at TEXT NOT NULL,
  updated_at TEXT NOT NULL,
  FOREIGN KEY(account_id) REFERENCES erp_accounts(id),
  FOREIGN KEY(batch_id) REFERENCES erp_inventory_batches(id),
  FOREIGN KEY(sku_id) REFERENCES erp_skus(id),
  FOREIGN KEY(inspector_id) REFERENCES erp_users(id)
);

CREATE TABLE IF NOT EXISTS erp_outbound_shipments (
  id TEXT PRIMARY KEY,
  account_id TEXT NOT NULL,
  shipment_no TEXT NOT NULL,
  sku_id TEXT NOT NULL,
  batch_id TEXT,
  qty INTEGER NOT NULL,
  boxes INTEGER,
  status TEXT NOT NULL DEFAULT 'draft',
  logistics_provider TEXT,
  tracking_no TEXT,
  photos_json TEXT NOT NULL DEFAULT '[]',
  warehouse_operator_id TEXT,
  shipped_at TEXT,
  confirmed_by TEXT,
  confirmed_at TEXT,
  remark TEXT,
  created_at TEXT NOT NULL,
  updated_at TEXT NOT NULL,
  UNIQUE(account_id, shipment_no),
  FOREIGN KEY(account_id) REFERENCES erp_accounts(id),
  FOREIGN KEY(sku_id) REFERENCES erp_skus(id),
  FOREIGN KEY(batch_id) REFERENCES erp_inventory_batches(id),
  FOREIGN KEY(warehouse_operator_id) REFERENCES erp_users(id),
  FOREIGN KEY(confirmed_by) REFERENCES erp_users(id)
);
